- name: Correr Test pase lo que pase
        run: |
          # Busca donde diablos está el archivo y muévelo a la raíz
          find . -name "Workshop.java" -exec cp {} . \;
          find . -name "WorkshopTest.java" -exec cp {} . \;
          
          # Compila y corre en la raíz
          wget https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
          wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
          javac -cp junit-4.13.2.jar Workshop.java WorkshopTest.java
          java -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore WorkshopTest
